In [1]:
import pandas as pd

In [2]:
excel_file_path = 'C:/Users/ASUS/OneDrive/Documents/實習/Rebas/CPBL_2023.xlsx'  # 請替換成你的 Excel 檔案路徑
sheet_name1 = 'AWAY-打席資訊'  # 請替換成你要載入的工作表名稱
sheet_name2 = 'HOME-打席資訊'

In [3]:
away = pd.read_excel(excel_file_path, sheet_name=sheet_name1)
home = pd.read_excel(excel_file_path, sheet_name=sheet_name2)

In [4]:
cols = ['客場','主場','投手','打席結果','落點1','落點2','彈道']

In [5]:
away_play = away[cols]
home_play = home[cols]

In [6]:
away_play = away_play.rename(columns={'客場': '對手', '主場': '球隊'})
home_play = home_play.rename(columns={'客場': '球隊', '主場': '對手'})

In [7]:
away_play

         對手           球隊   投手 打席結果  落點1  落點2   彈道
0      富邦悍將  統一7-ELEVEn獅  江承諺   FO  8.0   89    F
1      富邦悍將  統一7-ELEVEn獅  江承諺   1B  8.0   8S    L
2      富邦悍將  統一7-ELEVEn獅  江承諺   1B  7.0   7S    G
3      富邦悍將  統一7-ELEVEn獅  江承諺   FO  8.0  89D    F
4      富邦悍將  統一7-ELEVEn獅  江承諺   GO  4.0    4    G
...     ...          ...  ...  ...  ...  ...  ...
11752  樂天桃猿         中信兄弟  江忠城   FO  7.0    7    F
11753  樂天桃猿         中信兄弟  江忠城   FO  7.0    7    F
11754  樂天桃猿         中信兄弟  江忠城   FO  5.0    5    L
11755  樂天桃猿         中信兄弟  江忠城   GO  3.0    3    G
11756  樂天桃猿         中信兄弟  江忠城   SO  NaN  NaN  NaN

[11757 rows x 7 columns]

In [8]:
home_play

         球隊           對手   投手  打席結果  落點1   落點2   彈道
0      富邦悍將  統一7-ELEVEn獅  陳仕朋    FO  8.0   89D    F
1      富邦悍將  統一7-ELEVEn獅  陳仕朋    FO  7.0    7D    F
2      富邦悍將  統一7-ELEVEn獅  陳仕朋    GO  4.0     4    G
3      富邦悍將  統一7-ELEVEn獅  陳仕朋   uBB  NaN   NaN  NaN
4      富邦悍將  統一7-ELEVEn獅  陳仕朋    FO  8.0  89XD    F
...     ...          ...  ...   ...  ...   ...  ...
11309  樂天桃猿         中信兄弟  陳冠宇    SO  NaN   NaN  NaN
11310  樂天桃猿         中信兄弟   豪勁    1B  5.0     5    G
11311  樂天桃猿         中信兄弟   豪勁     E  5.0     5    G
11312  樂天桃猿         中信兄弟   豪勁    FO  9.0     9    F
11313  樂天桃猿         中信兄弟   豪勁  GIDP  4.0     4    G

[11314 rows x 7 columns]

In [9]:
summary = pd.concat([home_play,away_play], ignore_index=True)
summary

         球隊           對手   投手 打席結果  落點1   落點2   彈道
0      富邦悍將  統一7-ELEVEn獅  陳仕朋   FO  8.0   89D    F
1      富邦悍將  統一7-ELEVEn獅  陳仕朋   FO  7.0    7D    F
2      富邦悍將  統一7-ELEVEn獅  陳仕朋   GO  4.0     4    G
3      富邦悍將  統一7-ELEVEn獅  陳仕朋  uBB  NaN   NaN  NaN
4      富邦悍將  統一7-ELEVEn獅  陳仕朋   FO  8.0  89XD    F
...     ...          ...  ...  ...  ...   ...  ...
23066  中信兄弟         樂天桃猿  江忠城   FO  7.0     7    F
23067  中信兄弟         樂天桃猿  江忠城   FO  7.0     7    F
23068  中信兄弟         樂天桃猿  江忠城   FO  5.0     5    L
23069  中信兄弟         樂天桃猿  江忠城   GO  3.0     3    G
23070  中信兄弟         樂天桃猿  江忠城   SO  NaN   NaN  NaN

[23071 rows x 7 columns]

In [10]:
def calculate_so_go_count(series):
    so_count = (series == 'SO').sum()
    ubb_count = (series == 'uBB').sum()
    hbp_count = (series == 'HBP').sum()
    hr_count = (series == 'HR').sum()
    return pd.Series({'SO': so_count,
                      'HR':hr_count
                     , 'uBB':ubb_count
                     , 'HBP':hbp_count})

In [11]:
resault_away=away_play.groupby(['投手','球隊'])['打席結果'].apply(calculate_so_go_count).reset_index()
resault_away = resault_away.rename(columns={'球隊':'球隊','level_2': '打席結果', '打席結果': '次數'})
resault_away

      投手           球隊 打席結果  次數
0     伍茲         富邦悍將   SO   2
1     伍茲         富邦悍將   HR   0
2     伍茲         富邦悍將  uBB   9
3     伍茲         富邦悍將  HBP   1
4     伍鐸          味全龍   SO  12
..   ...          ...  ...  ..
551  黃弘毅         中信兄弟  HBP   0
552  黃竣彥  統一7-ELEVEn獅   SO   5
553  黃竣彥  統一7-ELEVEn獅   HR   0
554  黃竣彥  統一7-ELEVEn獅  uBB   9
555  黃竣彥  統一7-ELEVEn獅  HBP   1

[556 rows x 4 columns]

In [12]:
resault_home=home_play.groupby(['投手','球隊'])['打席結果'].apply(calculate_so_go_count).reset_index()
resault_home = resault_home.rename(columns={'球隊':'球隊','level_2':'打席結果', '打席結果':'次數'})
resault_home

      投手           球隊 打席結果  次數
0     伍茲         富邦悍將   SO   1
1     伍茲         富邦悍將   HR   0
2     伍茲         富邦悍將  uBB   5
3     伍茲         富邦悍將  HBP   0
4     伍鐸          味全龍   SO   8
..   ...          ...  ...  ..
551  黃弘毅         中信兄弟  HBP   0
552  黃竣彥  統一7-ELEVEn獅   SO   7
553  黃竣彥  統一7-ELEVEn獅   HR   1
554  黃竣彥  統一7-ELEVEn獅  uBB   2
555  黃竣彥  統一7-ELEVEn獅  HBP   0

[556 rows x 4 columns]

In [13]:
resault_away['次數'] = resault_away['次數'].astype(int)

resault_away = pd.pivot_table(resault_away, index=['投手', '球隊'], columns=['打席結果'], values=['次數'], aggfunc='sum', fill_value=0)

resault_away

                 次數
打席結果            HBP HR  SO uBB
投手  球隊
伍茲  富邦悍將          1  0   2   9
伍鐸  味全龍           4  2  12  16
余德龍 樂天桃猿          0  0   0   0
余謙  中信兄弟          2  3  13  15
傅于剛 統一7-ELEVEn獅   0  0   1   1
...              .. ..  ..  ..
黃保羅 富邦悍將          0  1   3   2
黃偉晟 樂天桃猿          1  0   5   6
黃子鵬 樂天桃猿          2  5  29  11
黃弘毅 中信兄弟          0  0   0   1
黃竣彥 統一7-ELEVEn獅   1  0   5   9

[139 rows x 4 columns]

In [14]:
resault_home['次數'] = resault_home['次數'].astype(int)

resault_home = pd.pivot_table(resault_home, index=['投手', '球隊'], columns=['打席結果'], values='次數', aggfunc='sum', fill_value=0)

resault_home

打席結果             HBP  HR  SO  uBB
投手  球隊
伍茲  富邦悍將           0   0   1    5
伍鐸  味全龍            1   1   8   11
余謙  中信兄弟           2   4  25    9
傅于剛 統一7-ELEVEn獅    0   1   0    1
克維斯 統一7-ELEVEn獅    1   2  49   24
...              ...  ..  ..  ...
黃偉晟 樂天桃猿           2   0   9    6
黃子宸 富邦悍將           0   0   0    0
黃子鵬 樂天桃猿           7   7  43   33
黃弘毅 中信兄弟           0   0   0    0
黃竣彥 統一7-ELEVEn獅    0   1   7    2

[139 rows x 4 columns]

In [15]:
merged = pd.merge(resault_away, resault_home, on=['投手', '球隊'])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22156\3971530146.py:1: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (2 levels on the left, 1 on the right)
  merged = pd.merge(resault_away, resault_home, on=['投手', '球隊'])

In [16]:
merged

                 (次數, HBP)  (次數, HR)  (次數, SO)  (次數, uBB)  HBP  HR  SO  uBB
投手  球隊
伍茲  富邦悍將                 1         0         2          9    0   0   1    5
伍鐸  味全龍                  4         2        12         16    1   1   8   11
余謙  中信兄弟                 2         3        13         15    2   4  25    9
傅于剛 統一7-ELEVEn獅          0         0         1          1    0   1   0    1
克維斯 統一7-ELEVEn獅          5         3        66         20    1   2  49   24
...                    ...       ...       ...        ...  ...  ..  ..  ...
黃保羅 富邦悍將                 0         1         3          2    0   0   2    3
黃偉晟 樂天桃猿                 1         0         5          6    2   0   9    6
黃子鵬 樂天桃猿                 2         5        29         11    7   7  43   33
黃弘毅 中信兄弟                 0         0         0          1    0   0   0    0
黃竣彥 統一7-ELEVEn獅          1         0         5          9    0   1   7    2

[131 rows x 8 columns]

In [17]:
merged['HBP'] = merged[('次數', 'HBP')] + merged['HBP']
merged['HR'] = merged[('次數', 'HR')] + merged['HR']
merged['SO'] = merged[('次數', 'SO')] + merged['SO']
merged['uBB'] = merged[('次數', 'uBB')] + merged['uBB']

In [18]:
merged

                 (次數, HBP)  (次數, HR)  (次數, SO)  (次數, uBB)  HBP  HR   SO  uBB
投手  球隊
伍茲  富邦悍將                 1         0         2          9    1   0    3   14
伍鐸  味全龍                  4         2        12         16    5   3   20   27
余謙  中信兄弟                 2         3        13         15    4   7   38   24
傅于剛 統一7-ELEVEn獅          0         0         1          1    0   1    1    2
克維斯 統一7-ELEVEn獅          5         3        66         20    6   5  115   44
...                    ...       ...       ...        ...  ...  ..  ...  ...
黃保羅 富邦悍將                 0         1         3          2    0   1    5    5
黃偉晟 樂天桃猿                 1         0         5          6    3   0   14   12
黃子鵬 樂天桃猿                 2         5        29         11    9  12   72   44
黃弘毅 中信兄弟                 0         0         0          1    0   0    0    1
黃竣彥 統一7-ELEVEn獅          1         0         5          9    1   1   12   11

[131 rows x 8 columns]

In [19]:
# 删除不需要的列
merged = merged.drop([('次數', 'HBP'), ('次數', 'HR'), ('次數', 'SO'), ('次數', 'uBB')], axis=1)
merged

                 HBP  HR   SO  uBB
投手  球隊
伍茲  富邦悍將           1   0    3   14
伍鐸  味全龍            5   3   20   27
余謙  中信兄弟           4   7   38   24
傅于剛 統一7-ELEVEn獅    0   1    1    2
克維斯 統一7-ELEVEn獅    6   5  115   44
...              ...  ..  ...  ...
黃保羅 富邦悍將           0   1    5    5
黃偉晟 樂天桃猿           3   0   14   12
黃子鵬 樂天桃猿           9  12   72   44
黃弘毅 中信兄弟           0   0    0    1
黃竣彥 統一7-ELEVEn獅    1   1   12   11

[131 rows x 4 columns]

In [20]:
def classify_fly_ball(row):
    #if row['彈道'] == 'F' and row['落點1'] in ['7.0','8.0','9.0']:
        #return '外野飛球'
    if row['彈道'] == 'P' and row['落點1'] not in ['7.0','8.0','9.0']:
        return '內野飛球'
    #elif row['彈道'] == 'P' and row['落點1'] in ['1.0','2.0','3.0','4.0','5.0','6.0']:
        #return '內野飛球'
    elif row['彈道'] == 'F' and row['落點1'] not in ['1.0','2.0','3.0','4.0','5.0','6.0']:
        return '外野飛球'
    elif row['彈道'] == 'L':
        return '平飛球'
    elif row['彈道'] == 'G':
        return '滾地球'
    else:
        return '其他'

summary['飛球分類'] = summary.apply(classify_fly_ball, axis=1)

# 打印结果
summary

         球隊           對手   投手 打席結果  落點1   落點2   彈道  飛球分類
0      富邦悍將  統一7-ELEVEn獅  陳仕朋   FO  8.0   89D    F  外野飛球
1      富邦悍將  統一7-ELEVEn獅  陳仕朋   FO  7.0    7D    F  外野飛球
2      富邦悍將  統一7-ELEVEn獅  陳仕朋   GO  4.0     4    G   滾地球
3      富邦悍將  統一7-ELEVEn獅  陳仕朋  uBB  NaN   NaN  NaN    其他
4      富邦悍將  統一7-ELEVEn獅  陳仕朋   FO  8.0  89XD    F  外野飛球
...     ...          ...  ...  ...  ...   ...  ...   ...
23066  中信兄弟         樂天桃猿  江忠城   FO  7.0     7    F  外野飛球
23067  中信兄弟         樂天桃猿  江忠城   FO  7.0     7    F  外野飛球
23068  中信兄弟         樂天桃猿  江忠城   FO  5.0     5    L   平飛球
23069  中信兄弟         樂天桃猿  江忠城   GO  3.0     3    G   滾地球
23070  中信兄弟         樂天桃猿  江忠城   SO  NaN   NaN  NaN    其他

[23071 rows x 8 columns]

In [21]:
def calculate_so_go_count(series):
    iff_count = (series == '內野飛球').sum()
    off_count = (series == '外野飛球').sum()
    ld_count = (series == '平飛球').sum()
    gr_count = (series == '滾地球').sum()
    return pd.Series({'內野飛球': iff_count,
                      '外野飛球':off_count
                     , '平飛球':ld_count
                     , '滾地球':gr_count})

In [22]:
resault2=summary.groupby(['投手','球隊'])['飛球分類'].apply(calculate_so_go_count).reset_index()
resault2 = resault2.rename(columns={'level_2': '擊球分類', '飛球分類': '次數'})

resault2['次數'] = resault2['次數'].astype(int)

final_resault2 = pd.pivot_table(resault2, index=['投手','球隊'], columns='擊球分類', values='次數', aggfunc='sum', fill_value=0)

final_resault2

擊球分類             內野飛球  外野飛球  平飛球  滾地球
投手  球隊
伍茲  富邦悍將            2     9    3   22
伍鐸  味全龍            12    98   39  130
余德龍 樂天桃猿            0     2    0    2
余謙  中信兄弟           13    62   27  109
傅于剛 統一7-ELEVEn獅     1     5    2    8
...               ...   ...  ...  ...
黃偉晟 樂天桃猿            6    35    6   57
黃子宸 富邦悍將            1     0    0    5
黃子鵬 樂天桃猿           46   163   66  250
黃弘毅 中信兄弟            0     1    0    4
黃竣彥 統一7-ELEVEn獅     9    30   15   30

[147 rows x 4 columns]

In [23]:
pitcher = pd.merge(merged, final_resault2,on=['投手','球隊'])

pitcher

                 HBP  HR   SO  uBB  內野飛球  外野飛球  平飛球  滾地球
投手  球隊
伍茲  富邦悍將           1   0    3   14     2     9    3   22
伍鐸  味全龍            5   3   20   27    12    98   39  130
余謙  中信兄弟           4   7   38   24    13    62   27  109
傅于剛 統一7-ELEVEn獅    0   1    1    2     1     5    2    8
克維斯 統一7-ELEVEn獅    6   5  115   44    16   100   37  140
...              ...  ..  ...  ...   ...   ...  ...  ...
黃保羅 富邦悍將           0   1    5    5     0     7    6    9
黃偉晟 樂天桃猿           3   0   14   12     6    35    6   57
黃子鵬 樂天桃猿           9  12   72   44    46   163   66  250
黃弘毅 中信兄弟           0   0    0    1     0     1    0    4
黃竣彥 統一7-ELEVEn獅    1   1   12   11     9    30   15   30

[131 rows x 8 columns]

In [24]:
pitcher.reset_index(drop=False, inplace=True)
pitcher = pitcher[['投手', '球隊', 'HBP', 'HR', 'SO', 'uBB', '內野飛球', '外野飛球', '平飛球', '滾地球']]
pitcher

      投手           球隊  HBP  HR   SO  uBB  內野飛球  外野飛球  平飛球  滾地球
0     伍茲         富邦悍將    1   0    3   14     2     9    3   22
1     伍鐸          味全龍    5   3   20   27    12    98   39  130
2     余謙         中信兄弟    4   7   38   24    13    62   27  109
3    傅于剛  統一7-ELEVEn獅    0   1    1    2     1     5    2    8
4    克維斯  統一7-ELEVEn獅    6   5  115   44    16   100   37  140
..   ...          ...  ...  ..  ...  ...   ...   ...  ...  ...
126  黃保羅         富邦悍將    0   1    5    5     0     7    6    9
127  黃偉晟         樂天桃猿    3   0   14   12     6    35    6   57
128  黃子鵬         樂天桃猿    9  12   72   44    46   163   66  250
129  黃弘毅         中信兄弟    0   0    0    1     0     1    0    4
130  黃竣彥  統一7-ELEVEn獅    1   1   12   11     9    30   15   30

[131 rows x 10 columns]

In [25]:
#計算聯盟定數
uBB = pitcher['uBB'].sum()
HBP = pitcher['HBP'].sum()
SO = pitcher['SO'].sum()
HR = pitcher['HR'].sum()
滾地球 = pitcher['滾地球'].sum()
IFF = pitcher['內野飛球'].sum()
OFF = pitcher['外野飛球'].sum()
平飛球 = pitcher['平飛球'].sum()
lg_ERA = 3.7

constant = (lg_ERA - (
    (0.354188 * uBB 
     + 0.372947 * HBP 
     - 0.304666 * SO 
     + 1.711948 * HR 
     - 0.076593 * 滾地球 
     -0.300934 * IFF
     + 0.048510 * OFF 
     + 0.307350 * 平飛球)) /
    (SO + 0.709957 * 滾地球 + 0.290352 * 平飛球 + 0.987002 * IFF + 0.711651 * OFF) * 27
)
constant

3.4377164595959897

In [26]:
lg_tRA = (0.354188 * uBB 
     + 0.372947 * HBP 
     - 0.304666 * SO 
     + 1.711948 * HR 
     - 0.077254 * 滾地球 
     -0.300934 * IFF
     + 0.048510 * OFF 
     + 0.307350 * 平飛球)/((SO + 0.709957 * 滾地球 + 0.290352 * 平飛球 + 0.987002 * IFF + 0.711651 * OFF) * 27)+constant
                
lg_tRA

3.4380636410471386

In [27]:
pitcher['tRA']=((pitcher['uBB']*0.354188
                 +pitcher['HBP']*0.372947
                 -pitcher['SO']*0.304666
                 +pitcher['HR']*1.711948
                 -pitcher['滾地球']* 0.076593
                 -pitcher['內野飛球']*0.300934
                 +pitcher['外野飛球']*0.048510
                 +pitcher['平飛球']*0.307350)/
                (pitcher['SO']
                 +pitcher['滾地球']*0.709957
                +pitcher['平飛球']*0.290352
                +pitcher['內野飛球']*0.987002
                +pitcher['外野飛球']*0.711651)*27)+constant

In [28]:
pitcher

      投手           球隊  HBP  HR   SO  uBB  內野飛球  外野飛球  平飛球  滾地球       tRA
0     伍茲         富邦悍將    1   0    3   14     2     9    3   22  6.818225
1     伍鐸          味全龍    5   3   20   27    12    98   39  130  5.232770
2     余謙         中信兄弟    4   7   38   24    13    62   27  109  4.852903
3    傅于剛  統一7-ELEVEn獅    0   1    1    2     1     5    2    8  8.147272
4    克維斯  統一7-ELEVEn獅    6   5  115   44    16   100   37  140  2.748221
..   ...          ...  ...  ..  ...  ...   ...   ...  ...  ...       ...
126  黃保羅         富邦悍將    0   1    5    5     0     7    6    9  8.586152
127  黃偉晟         樂天桃猿    3   0   14   12     6    35    6   57  2.964444
128  黃子鵬         樂天桃猿    9  12   72   44    46   163   66  250  4.238150
129  黃弘毅         中信兄弟    0   0    0    1     0     1    0    4  4.170032
130  黃竣彥  統一7-ELEVEn獅    1   1   12   11     9    30   15   30  4.783738

[131 rows x 11 columns]

In [29]:
#pitcher.to_excel('2023tRA.xlsx', index=True)